[package]
name = "blamefetch"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
colored = "3.1.1"
dirs = "6.0.0"
hostname = "0.4.2"
os_info = "3.15.0"
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
sysinfo = "0.39.6"
toml = "1.1.4"
whoami = "2.1.2"

[dev-dependencies]
tempfile = "3.27.0"
