use crate::git::GitData;
use crate::sources::CoAuthor;

/// One line of the commit body: a `Co-Authored-By` trailer or a raw text line
/// (an empty string renders an indented blank line).
pub enum BodyItem {
    Trailer(CoAuthor),
    Text(String),
}

pub struct RenderOptions {
    pub color: bool,
}

pub fn render_commit(git: &GitData, items: &[BodyItem], opts: &RenderOptions) -> String {
    let mut out = String::new();

    out.push_str(&format!("{} {}\n", word("commit", opts.color), git.hash));
    out.push_str(&format!(
        "{}: {} <{}>\n",
        word("Author", opts.color),
        sanitize_terminal_text(git.author_name.as_deref().unwrap_or_default()),
        sanitize_terminal_text(git.author_email.as_deref().unwrap_or_default())
    ));
    if let Some(date) = &git.date {
        // Three spaces after the colon, like git: the label column is padded to
        // 8 characters so the value lines up with "Author: ".
        out.push_str(&format!("{}:   {}\n", word("Date", opts.color), date));
    }
    out.push('\n');

    // Compose the body (message + items), then indent every line by four
    // spaces to match git's rendering of a commit message.
    let mut body = String::new();
    if !git.message.is_empty() {
        body.push_str(&sanitize_terminal_text(git.message.trim_end()));
        body.push('\n');
        body.push('\n');
    }
    for item in items {
        match item {
            BodyItem::Trailer(ca) => body.push_str(&format!(
                "{}: {} <{}>\n",
                word("Co-Authored-By", opts.color),
                ca.name,
                ca.email
            )),
            BodyItem::Text(line) => {
                body.push_str(line);
                body.push('\n');
            }
        }
    }
    for line in body.lines() {
        out.push_str("    ");
        out.push_str(line);
        out.push('\n');
    }

    out
}

/// Strips terminal control bytes (C0 controls and DEL, per `char::is_control`)
/// from text that will be printed, keeping `\n` and `\t` so multi-line commit
/// messages and indentation survive. Without the ESC leader, CSI/OSC
/// sequences degrade to inert visible text, so a crafted commit message
/// cannot drive the terminal.
fn sanitize_terminal_text(s: &str) -> String {
    s.chars()
        .filter(|c| !c.is_control() || *c == '\n' || *c == '\t')
        .collect()
}

fn word(s: &str, color: bool) -> String {
    if color {
        use colored::Colorize;
        s.bold().cyan().to_string()
    } else {
        s.to_string()
    }
}

#[cfg(test)]
mod tests {
    use crate::git::GitData;
    use crate::sources::CoAuthor;

    use super::{BodyItem, RenderOptions, render_commit};

    fn git() -> GitData {
        GitData {
            hash: "ab".repeat(20),
            message: "feat: test".to_string(),
            author_name: Some("Ann".to_string()),
            author_email: Some("ann@x.com".to_string()),
            date: Some("Thu Aug 6 05:32:10 2026 +0800".to_string()),
        }
    }

    fn git_without_date() -> GitData {
        GitData {
            date: None,
            ..git()
        }
    }

    fn trailer(name: &str, email: &str) -> BodyItem {
        BodyItem::Trailer(CoAuthor {
            name: name.to_string(),
            email: email.to_string(),
        })
    }

    fn opts() -> RenderOptions {
        RenderOptions { color: false }
    }

    #[test]
    fn header_and_message() {
        let out = render_commit(&git(), &[], &opts());
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(lines[0], format!("commit {}", "ab".repeat(20)));
        assert_eq!(lines[1], "Author: Ann <ann@x.com>");
        assert_eq!(lines[2], "Date:   Thu Aug 6 05:32:10 2026 +0800");
        assert!(lines[3].is_empty());
        assert_eq!(lines[4], "    feat: test");
    }

    #[test]
    fn no_date_line_when_date_missing() {
        let out = render_commit(&git_without_date(), &[], &opts());
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(lines[1], "Author: Ann <ann@x.com>");
        assert!(lines[2].is_empty(), "no Date line when date is None");
        assert_eq!(lines[3], "    feat: test");
    }

    #[test]
    fn items_in_order_mixed_text_and_trailers() {
        let items = vec![
            trailer("NixOS 26.11", "os@system.invalid"),
            BodyItem::Text("This commit is generated by Bot".to_string()),
            trailer("Sample 5.0", "noreply@example.com"),
        ];
        let out = render_commit(&git(), &items, &opts());
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(
            lines[6],
            "    Co-Authored-By: NixOS 26.11 <os@system.invalid>"
        );
        assert_eq!(lines[7], "    This commit is generated by Bot");
        assert_eq!(
            lines[8],
            "    Co-Authored-By: Sample 5.0 <noreply@example.com>"
        );
        assert_eq!(lines.len(), 9);
    }

    #[test]
    fn empty_text_renders_blank_line() {
        let items = vec![BodyItem::Text(String::new()), trailer("Only", "only@x.com")];
        let out = render_commit(&git(), &items, &opts());
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(
            lines[5], "    ",
            "message paragraph keeps its blank separator"
        );
        assert_eq!(
            lines[6], "    ",
            "an explicit empty text line renders an indented blank line"
        );
        assert_eq!(lines[7], "    Co-Authored-By: Only <only@x.com>");
        assert_eq!(lines.len(), 8);
    }

    #[test]
    fn no_trailing_blank_without_text_items() {
        let items = vec![trailer("NixOS 26.11", "os@system.invalid")];
        let out = render_commit(&git(), &items, &opts());
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(
            *lines.last().unwrap(),
            "    Co-Authored-By: NixOS 26.11 <os@system.invalid>"
        );
    }

    /// No control bytes other than `\n`/`\t` may survive rendering — ESC is
    /// the leader of every CSI/OSC sequence, so stripping it is sufficient to
    /// neuter terminal injection; BEL (OSC terminator) must go too.
    fn assert_no_terminal_controls(out: &str) {
        assert!(
            out.chars()
                .all(|c| !c.is_control() || c == '\n' || c == '\t'),
            "control bytes must be stripped: {out:?}"
        );
    }

    #[test]
    fn strips_escape_sequences_from_commit_message() {
        // OSC title-set, BEL, clear-screen, and color CSI sequences: all must
        // be stripped so a crafted commit cannot drive the terminal.
        let g = GitData {
            message: "feat: \x1b]0;EVIL-TITLE\x07\x1b[2J\x1b[31mRED\x1b[0m".to_string(),
            ..git()
        };
        let out = render_commit(&g, &[], &opts());
        assert_no_terminal_controls(&out);
        assert!(out.contains("RED"), "visible message text is preserved");
    }

    #[test]
    fn strips_escape_sequences_from_author_fields() {
        let g = GitData {
            author_name: Some("Ann\x1b[31m".to_string()),
            author_email: Some("ann@x.com\x1b]0;EVIL\x07".to_string()),
            ..git()
        };
        let out = render_commit(&g, &[], &opts());
        assert_no_terminal_controls(&out);
        assert!(out.contains("Author: Ann"), "author name text is preserved");
        assert!(
            out.contains("ann@x.com"),
            "author email text is preserved: {out:?}"
        );
    }

    #[test]
    fn preserves_newlines_and_tabs_in_message() {
        // Sanitization must not flatten multi-line messages or indentation.
        let g = GitData {
            message: "line one\n\tindented\nline three".to_string(),
            ..git()
        };
        let out = render_commit(&g, &[], &opts());
        assert!(out.contains("    line one"));
        assert!(
            out.contains("    \tindented"),
            "tab must survive sanitization: {out:?}"
        );
        assert!(out.contains("    line three"));
    }
}
